apiVersion: v1
kind: Secret
metadata:
  name: chat-secrets
  namespace: chat-app
  labels:
    app.kubernetes.io/name: p312-chat
type: Opaque
stringData:
  POSTGRES_USER: "chat_user"
  POSTGRES_PASSWORD: "chat_secure_password_replace_in_prod"
  JWT_SECRET: "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
  AWS_ACCESS_KEY_ID: "your-s3-access-key"
  AWS_SECRET_ACCESS_KEY: "your-s3-secret-key"
